# Generated by Django 3.2.8 on 2021-10-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendations',
            old_name='client_id',
            new_name='id_client',
        ),
    ]
