# Generated by Django 3.2.8 on 2021-10-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_client_id_recomendations_id_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
            ],
        ),
    ]
