# Generated by Django 3.2.8 on 2021-10-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.CharField(max_length=50)),
                ('id_book', models.CharField(max_length=50)),
                ('start_read', models.DateField()),
                ('finish_read', models.DateField()),
            ],
        ),
    ]
